harehare/mq

README.md, crates/mq-formatter/src/formatter.rs, crates/mq-lang/benches/benchmark.rs, crates/mq-lang/builtin.mq, crates/mq-lang/src/ast/node.rs, crates/mq-lang/src/ast/parser.rs, crates/mq-lang/src/cst/node.rs, crates/mq-lang/src/cst/parser.rs, crates/mq-lang/src/eval.rs, crates/mq-lang/src/eval/builtin.rs, crates/mq-lang/src/eval/runtime_value.rs, crates/mq-lang/src/lexer.rs, crates/mq-lang/src/lexer/token.rs, crates/mq-lang/src/optimizer.rs, crates/mq-lang/tests/integration_tests.rs, crates/mq-wasm/src/script.rs, docs/books/src/SUMMARY.md, docs/books/src/reference/nodes.md, docs/books/src/sitemap.xml, docs/books/src/start/example.md, editors/vscode/mq.tmLanguage.json, editors/vscode/package.json, editors/vscode/snippets/mq.json, playground/src/Playground.tsx, src/cli.rs, tests/integration_tests.rs
https://github.com/harehare/mq/issues/161
=> ✨ feat(mq-lang): Add `nodes` keyword for processing all Markdown nodes

crates/mq-hir/src/builtin.rs, crates/mq-hir/src/hir.rs, crates/mq-lang/builtin.mq, crates/mq-lang/src/eval/builtin.rs, crates/mq-lang/src/lib.rs, crates/mq-lang/tests/integration_tests.rs
https://github.com/harehare/mq/issues/161
=> :rocket: Add `sort_by` functions

crates/mq-formatter/src/formatter.rs
https://github.com/harehare/mq/issues/278
=> 🐛 Fix string literal formatting

AGENTS.md
This commit introduces the AGENTS.md file, which provides an overview of the various components (crates and packages) that constitute the mq project.
Each component's purpose and primary functionality are summarized based on available README files or inferred from their names.
=> Add AGENTS.md documenting project components

crates/mq-lang/src/ast/parser.rs
- Add is_first_binary_op flag to track operator precedence
- Extract is_binary_op helper function for better code organization
- Improve handling of chained binary operations with proper recursion
- Add comprehensive test case for binary operator chaining (2 > 1 or 2 > 1)
- Refactor parse_equality_expr to handle complex operator combinations
=> ✨ feat(lang): improve binary operator chaining in parser

crates/mq-lang/src/lexer.rs
Implement hex escape sequences (\xNN) in string literals and string segments. Adds hex_escape function to parse 2-digit hexadecimal escape sequences and includes comprehensive test coverage for escape sequence parsing.
=> ✨ feat(lexer): add hex escape sequence support for string literals

crates/mq-formatter/src/formatter.rs
Adds proper indentation handling for pipe-let expressions within if-else statements inside while loops. The formatter now correctly applies 2-level indentation for such cases, ensuring proper code formatting.
=> 🐛 fix(formatter): improve indentation for pipe-let expressions in conditionals

crates/mq-lsp/src/hover.rs
- Simplify hover response logic by removing unnecessary chaining
- Improve pattern matching structure for better readability
- Add test for builtin function hover functionality
- Clean up range handling in hover response
=> ♻️ refactor(lsp): Improve hover response code structure and add builtin function test

crates/mq-lang/src/ast/parser.rs
Fix incorrect operator precedence handling in expression parsing by implementing proper precedence climbing algorithm. The previous implementation parsed operators left-to-right without respecting precedence rules, causing incorrect evaluation of complex expressions.
Changes:
- Add binary_op_precedence() to define correct operator precedence levels
- Add binary_op_function_name() helper for mapping operators to functions
- Replace parse_equality_expr() logic with precedence climbing algorithm
- Implement parse_binary_op() with proper precedence and associativity handling
=> 🐛 fix(parser): Fix binary operator precedence parsing

README.md, scripts/update_version.sh
- Add automatic README.md version update functionality to update_version.sh
- Update Docker and Cargo install commands with new version references
- Include README path variable for better maintainability
- Update README.md to reflect current version v0.2.14
=> ✨ feat(scripts): Improve version update script to automatically update README

crates/mq-formatter/src/formatter.rs
Fix indentation calculation for functions used as call arguments by using current line context instead of passed indent level. This resolves formatting issues where nested functions were not properly aligned with their calling context.
Changes:
- Add current_line_indent() method to calculate proper indentation
- Update format_node to use current line indentation for nested structures
- Add test cases to verify correct formatting of functions as arguments
=> 🐛 fix(formatter): correct indentation for nested function calls as arguments

crates/mq-lang/src/ast/parser.rs, crates/mq-lang/src/cst/parser.rs
Enhance both AST and CST parsers to support bracket access syntax on the self keyword, enabling expressions like self[0] and self["key"]. This allows more flexible data access patterns when using self references.
- Add bracket access parsing logic to parse_self in both parsers
- Include comprehensive test cases for numeric and string bracket access
- Maintain backward compatibility with existing self keyword usage
=> ✨ feat(parser): add bracket access support for self keyword

crates/mq-lang/src/cst/parser.rs
Add If token kind to pattern matching in parser to enable conditional expression parsing functionality.
=> ✨ feat(parser): add If token support to CST parser

crates/mq-lang/modules/csv.mq, docs/books/src/start/example.md
- Remove unnecessary variable assignment in _parse_csv_field function
- Reorganize example documentation with better categorization
- Add more comprehensive examples including maps, filters, and file processing
=> ♻️ refactor(csv): simplify field parsing logic and enhance documentation

crates/mq-lang/src/eval.rs, crates/mq-lang/src/eval/module.rs
- Split Module struct to distinguish between includes and functions
- Update module loading logic to process includes before functions
- Add proper error handling for include expressions
- Update tests to reflect new module structure
=> ♻️ refactor(eval): separate module includes and function definitions

crates/mq-hir/src/hir.rs, crates/mq-lsp/src/server.rs
- Add unused_functions() method to HIR for detecting unused user-defined functions
- Integrate unused function detection into LSP server diagnostics
- Add comprehensive tests for unused function detection
- Display unused functions as warnings in LSP clients
=> ✨ feat(hir,lsp): add unused function detection and warnings

crates/mq-lang/modules/csv.mq, crates/mq-lang/modules/json.mq, crates/mq-lang/modules/yaml.mq
- Rename CSV parsing functions with clearer prefixes (_parse_csv_*)
- Move JSON helper functions inside main functions for better encapsulation
- Remove unused code and comments in YAML module
=> ♻️ refactor(modules): improve code organization and naming

.gitignore, .vscode/launch.json
- Remove .vscode from .gitignore to allow debug configs
- Add launch.json with VSCode extension and Rust debugging setups
- Support for debugging mq VSCode extension development
- Enable LLDB debugging for Rust code
=> ✨ feat(dev): add VS Code debugging configurations

packages/playground/src/Playground.tsx, packages/playground/src/components/GitHubButton.tsx, packages/tools/src/App.tsx, packages/tools/src/components/GitHubButton.tsx
- Renamed GitHubStarButton component to GitHubButton for consistency
- Updated imports in playground and tools packages
- Removed old component files and added new ones
=> ♻️ refactor(components): rename GitHubStarButton to GitHubButton

.github/codecov.yml, crates/mq-dap/src/adapter.rs, crates/mq-dap/src/log.rs, crates/mq-dap/src/protocol.rs, crates/mq-dap/src/server.rs, crates/mq-lang/src/engine.rs, crates/mq-lang/src/eval/env.rs, justfile
- Add comprehensive unit tests for MqAdapter launch and stack trace functionality
- Add test coverage for DebugConsoleWriter including error handling scenarios
- Add extensive parameterized tests for Variable display and environment functionality
- Add new unit tests for Engine switch_env and debug source code methods
- Refactor DAP protocol structs to support Serialize trait for better testability
- Update codecov configuration to include more targeted DAP coverage exclusions
- Update test-cov command to include all features for comprehensive coverage
- Remove duplicate server tests and improve error type definitions for better Send+Sync compliance
=> ✅ test: improve DAP test coverage and refactor test configuration

editors/vscode/src/extension.ts, editors/vscode/src/providers/debugger.ts
Optimizes VS Code extension installation process by checking if mq-dbg is already available before attempting to install both LSP and DAP servers. This prevents unnecessary reinstallation and improves user experience.
=> ✨ feat(vscode): improve DAP installation with conditional check

docs/books/src/start/debugger.md, docs/books/src/start/install.md, scripts/install.sh
- Add INSTALL_DEBUG flag and --with-debug command line option
- Implement install_mq_dbg() function with cross-platform support
- Enhanced checksum verification for debug binary
- Update verification process to check both binaries when debug is enabled
- Improve post-installation messages to show installed tools
- Add debug-specific help and examples in post-install output
=> ✨ feat(install): add --with-debug option to install mq-dbg alongside mq

crates/mq-lang/builtin.mq, crates/mq-lang/src/ast/parser.rs, crates/mq-lang/src/cst/parser.rs, crates/mq-lang/src/lexer.rs, crates/mq-lang/src/lexer/token.rs, docs/books/src/reference/try_catch.md
- Add Question token to lexer for ? syntax
- Support try without catch (returns None on error)
- Support func()? shorthand for try-catch
- Add is_next_token() helper for parser lookahead
- Add comprehensive tests for both syntax forms
- Fix indentation in builtin.mq transpose function
=> ✨ feat(lang): add optional error handling with ? operator
