harehare/mq

crates/mq-lang/benches/benchmark.rs
crates/mq-lang/src/optimizer.rs

This commit introduces several improvements to the mq-lang optimizer:
1.  **Constant Folding for Boolean and Comparison Operations:**
*   The optimizer can now evaluate boolean operations (`and`, `or`, `not`) and comparison operations (`eq`, `neq`, `gt`, `gte`, `lt`, `lte`) at compile time if their arguments are literal values.
*   This reduces runtime overhead for expressions with constant conditions or comparisons.
2.  **Basic Dead Code Elimination (DCE):**
*   Unused `let` bindings are now removed from the AST.
*   A two-pass approach is used: the first pass collects all used identifiers, and the second pass removes `Let` nodes whose identifiers are not in the used set.
*   The `constant_table` is updated accordingly if a constant-propagated variable is eliminated.
3.  **New …

feat: Enhance optimizer with constant folding and dead code elimination

---

flake.nix

Sorry, forgot to update it before the merge.
if we don't change it any nix build will get this error:
```bash
i $ nix build .#mq
error: Cannot build '/nix/store/v90zzbnyn3hbsldwi5izkjvjv2zy0892-mq-unstable.drv'.
Reason: builder failed with exit code 1.
Output paths:
/nix/store/d4vj4z927vawrdxd2d1y2amxyvk6pcga-mq-unstable
Last 25 log lines:
> ---
> > version = "4.5.39"
> 325c325
> < checksum = "ed93b9805f8ba930df42c2590f05453d5ec36cbb85d018868a5b24d31f6ac000"
> ---
> > checksum = "fd60e63e9be68e5fb56422e397cf9baddded06dae1d2e523401542383bc72a9f"
> 333c333
> < version = "4.5.38"
> ---
> > version = "4.5.39"
> 335c335
> < checksum = "379026ff283facf611b0ea629334361c4211d1b12ee01024eec1591133b04120"
> ---
> > checksum = "89cc6392a1f72bbeb820d71f32108f61fdaf18bc526e1d23954168a67759ef51"
>
> …
```

build mq from the local source instead of fetching from Git in flake.nix

---

editors/vscode/package-lock.json
editors/vscode/src/extension.ts
editors/vscode/tsconfig.json

This commit introduces a "Copy result to clipboard" feature in the VSCode extension.
When an `mq` command is executed via the extension (e.g., "mq: Run Selected Text" or "mq: Execute mq File"), after the result is displayed in the output panel, an information message now appears with a "Copy result to clipboard" button.
Clicking this button copies the entire result of the `mq` command to the system clipboard. A confirmation message is shown upon successful copy, and an error message if the copy operation fails.
This enhancement improves your workflow by allowing easy access to command results for pasting into other applications or documents.

feat: Add copy to clipboard functionality for VSCode extension

---

crates/mq-formatter/src/formatter.rs
crates/mq-lang/src/cst/parser.rs

- Extract string escaping logic into dedicated escape_string method
- Add support for hex escape sequences (\xXX) for control characters
- Improve handling of Unicode control characters with \u{xxxx} format
- Add comprehensive test coverage for escape sequence formatting
- Update parser tests to include escape sequence validation

♻️ refactor(formatter): improve string escape handling with hex format support

---

crates/mq-formatter/src/formatter.rs
crates/mq-hir/src/hir.rs
crates/mq-hir/src/symbol.rs
crates/mq-lang/src/ast/parser.rs
crates/mq-lang/src/cst/node.rs
crates/mq-lang/src/cst/parser.rs
crates/mq-lang/src/lexer.rs
crates/mq-lang/src/lexer/token.rs
crates/mq-lang/src/lib.rs
crates/mq-lsp/src/semantic_tokens.rs
editors/vscode/mq.tmLanguage.json
packages/playground/src/Playground.tsx

Implements comprehensive unary operator support across the mq language stack:
- Add UnaryOp enum with Not variant to CST and HIR
- Implement unary operator parsing in AST and CST parsers
- Add formatter support for unary operations
- Include HIR symbol handling for unary operators
- Add LSP semantic token support for unary operators
- Add comprehensive test coverage for NOT operator functionality
The NOT operator (\!) can now be used with boolean literals and variables, following standard logical negation semantics.

✨ feat(lang): add unary operator support with NOT operator

---

editors/vscode/package.json
editors/vscode/src/extension.ts

Add mq.enableCodeLens setting to allow users to enable/disable CodeLens functionality in the VSCode extension. Includes dynamic provider management with proper cleanup and configuration change watching.

✨ feat(vscode): Add configurable CodeLens toggle

---

crates/mq-formatter/src/formatter.rs
crates/mq-hir/src/hir.rs
crates/mq-lang/src/cst/node.rs

- Move End token handling logic to append_token method for consistency
- Add End variant to CstNodeKind enum in mq-lang
- Update pattern matches to include End token in formatter and HIR
- Consolidate End token formatting logic for better maintainability

🐛 fix(formatter): Improve End token handling and code organization

---

crates/mq-lang/builtin.mq
crates/mq-lang/examples/rule110.rs
crates/mq-lang/src/eval.rs
crates/mq-lang/src/eval/builtin.rs
editors/vscode/package-lock.json
packages/playground/src/Playground.tsx

- Remove nth builtin function from eval/builtin.rs
- Extend get function to support all nth functionality (arrays, strings, markdown)
- Update all nth() calls to get() in builtin.mq library functions
- Update rule110 example to use get() instead of nth()
- Update test cases from nth_* to get_* naming
- Update playground example to use get() syntax
- Bump VSCode extension version to 0.2.14

♻️ refactor(lang): Remove nth function and integrate functionality into get

---

crates/mq-lang/src/lexer.rs

Reorder alt parser in literals function to prioritize string_literal first for better parsing performance on common cases.

Fix literal parsing order in lexer

---

crates/mq-lang/src/ast/parser.rs
crates/mq-lang/src/cst/parser.rs
crates/mq-lang/src/eval.rs
crates/mq-lang/src/lexer/token.rs

Fix CST parser to properly handle Not tokens as unary operators in function call arguments. Previously the parser would fail to recognize Not tokens in function call contexts.
- Add Not token to primary expression parsing in CST parser
- Add comprehensive test case for function calls with Not operator arguments
- Include additional test coverage for break/continue statements in AST parser
- Add evaluator tests for break/continue control flow in foreach loops

🐛 fix(parser): fix parser for 'Not' token in function calls

---

crates/mq-formatter/src/formatter.rs
crates/mq-lang/src/ast/parser.rs

- Fix formatter to avoid adding unnecessary spaces when output is empty
- Add support for comments before elif statements in parser
- Add comprehensive test cases for comment handling scenarios
- Ensure proper formatting of code with comments at the beginning

🐛 fix(parser,formatter): improve comment handling in parser and formatter

---

crates/mq-lang/builtin.mq
crates/mq-lang/src/eval.rs
crates/mq-lang/src/eval/builtin.rs

Enhanced the slice function to support negative indices for arrays, strings, and markdown nodes, following Python-style negative indexing where -1 refers to the last element. Added comprehensive test coverage for all combinations of positive and negative indices.

✨ feat(lang): add negative index support to slice function

---

crates/mq-formatter/src/formatter.rs
crates/mq-lang/src/cst/node.rs
crates/mq-lang/src/cst/parser.rs

Add Group node kind and parsing logic for parenthesized expressions. Includes formatter support and comprehensive test coverage.

🐛 fix(parser): add group expression parsing support

---

crates/mq-lang/src/cst/parser.rs

- Add support for LParen token in parse_primary method
- Add comprehensive test case for if statements with grouped binary operations
- Enhance parser robustness for parenthesized expressions

🐛 fix(parser): improve parentheses handling in expression parsing

---

crates/mq-lang/src/cst/parser.rs

Extend parse_arg function to recognize Until, Foreach, and While token kinds as valid argument patterns, enabling loop constructs to be parsed correctly in argument contexts.

✨ feat(parser): add support for loop keywords in argument parsing

---

crates/mq-python/src/lib.rs
crates/mq-python/src/mq/mq.pyi
crates/mq-python/uv.lock
crates/mq-wasm/src/script.rs

- Add InputFormat::Raw and InputFormat::Null variants to Python bindings
- Map new formats to corresponding mq_lang functions (raw_input, null_input)
- Update type hints in mq.pyi to include new format options
- Fix clippy warning by using PascalCase for enum variants

✨ feat(python): add RAW and NULL input format support

---

crates/mq-lang/modules/json.mq
docs/books/src/SUMMARY.md
docs/books/src/reference/json_functions.md
docs/books/src/sitemap.xml
scripts/tests/json_tests.mq

- Add detailed documentation for json_parse(), json_stringify(), and json_to_markdown_table()
- Include examples, parameter descriptions, and type conversion details
- Document supported JSON format features and error handling
- Update SUMMARY.md to include JSON functions reference
- Fix JSON object value parsing validation in json.mq module

📝 docs(json): add comprehensive JSON functions reference documentation

---

crates/mq-cli/src/cli.rs
crates/mq-cli/tests/integration_tests.rs

Add command-line flags --json, --csv, --yaml, and --test to automatically include built-in modules in queries. The flags prepend appropriate include statements to the user's query, making it more convenient to access module functions without manual includes.

✨ feat(cli): add module inclusion flags for built-in modules

---

crates/mq-hir/src/error.rs
crates/mq-hir/src/lib.rs
crates/mq-lsp/src/server.rs

Implements static analysis to detect and warn about code that comes after halt() function calls, which are unreachable by definition.
- Add HirWarning enum with UnreachableCode variant in mq-hir/error.rs
- Implement warnings() method to detect unreachable code patterns
- Add warning_ranges() method for LSP diagnostic integration
- Extend LSP server to publish warnings with appropriate severity
- Add comprehensive test coverage for warning detection and LSP integration
- Export HirError and HirWarning types in public API

✨ feat(hir,lsp): add unreachable code warnings after halt() calls

---

Cargo.lock
crates/mq-mcp/Cargo.toml
crates/mq-mcp/src/server.rs

- Update rmcp dependency to version 0.6.1 in mq-mcp crate
- Fix import path: tool::Parameters -> wrapper::Parameters
- Update content handling to work with new rmcp API
- Simplify iterator patterns in test code

📦 build(mcp): upgrade rmcp dependency from 0.5.0 to 0.6.1

---

crates/mq-lang/src/ast.rs
crates/mq-lang/src/ast/constants.rs
crates/mq-lang/src/ast/parser.rs
crates/mq-lang/src/eval/builtin.rs

- Create new constants.rs module in ast crate with common function name constants
- Replace all hardcoded string literals in parser.rs with references to constants
- Improves maintainability and reduces risk of typos in function name strings
- Updated all binary operators, unary operators, and builtin function calls to use constants

♻️ refactor(lang): extract hardcoded function names to constants module

---

crates/mq-cli/src/cli.rs
crates/mq-cli/tests/integration_tests.rs

- Add --stream flag to enable line-by-line processing of large files
- Refactor CLI execution logic to support both batch and streaming modes
- Implement process_streaming() and process_lines() methods for efficient memory usage
- Add integration test for streaming functionality
- Maintain backward compatibility with existing batch processing mode

✨ feat(cli): add streaming mode for processing large files line by line

---

crates/mq-cli/Cargo.toml
crates/mq-cli/tests/integration_tests.rs
crates/mq-lang/Cargo.toml
crates/mq-lang/builtin.mq
crates/mq-lang/src/eval/builtin.rs

Add file I/O capability to mq language with a new read_file builtin function that allows reading file contents from the filesystem. The functionality is gated behind a file-io feature flag to keep the core language minimal.
Changes:
- Add read_file builtin function in mq-lang with file-io feature guard
- Enable file-io feature in mq-cli for CLI usage
- Add integration test for read_file functionality
- Fix indentation in builtin.mq filter function

✨ feat(lang): add read_file builtin function with file-io feature

---

crates/mq-lang/src/eval.rs
crates/mq-lang/src/eval/builtin.rs

- Extended mul function to handle string × number operations (e.g., "te" * 2 = "tete")
- Updated test case to verify string multiplication functionality
- Maintains backward compatibility with existing number multiplication

✨ feat(lang): add string multiplication support to mul builtin function

---

crates/mq-formatter/src/formatter.rs

Ensures the formatter adds a space before 'end' keyword when it doesn't have a newline, preventing malformed output like 'fn():1end'.

🐛 fix(formatter): add proper spacing before end keyword

---

crates/mq-cli/src/cli.rs
crates/mq-cli/src/debugger.rs
crates/mq-lang/Cargo.toml
crates/mq-lang/README.md
crates/mq-lang/benches/benchmark.rs
crates/mq-lang/src/ast.rs
crates/mq-lang/src/ast/node.rs
crates/mq-lang/src/ast/parser.rs
crates/mq-lang/src/engine.rs
crates/mq-lang/src/error.rs
crates/mq-lang/src/eval.rs
crates/mq-lang/src/eval/builtin.rs
crates/mq-lang/src/eval/debugger.rs
crates/mq-lang/src/eval/env.rs
crates/mq-lang/src/eval/module.rs
crates/mq-lang/src/eval/runtime_value.rs
crates/mq-lang/src/lib.rs
crates/mq-lang/src/optimizer.rs
crates/mq-lang/tests/integration_tests.rs
crates/mq-lsp/src/execute_command.rs
crates/mq-wasm/src/script.rs
justfile

- Introduce 'sync' feature flag for conditional compilation between single-threaded and multi-threaded modes
- Add Shared<T> type alias that switches between Rc<T> (non-sync) and Arc<T> (sync mode)
- Add SharedCell<T> type alias that switches between RefCell<T> (non-sync) and RwLock<T> (sync mode)
- Refactor all crates to use new type aliases instead of hardcoded Rc/RefCell
- Update debugger feature to depend on sync feature for thread safety
- Add helper functions token_alloc() and get_token() with conditional compilation
- Update documentation and examples to use new type aliases
This enables the mq language to be safely used in both single-threaded and multi-threaded environments depending on feature flags, improving flexibility and thread safety when needed.

♻️ refactor: add conditional sync support with Shared and SharedCell type aliases

---

crates/mq-lsp/src/server.rs

Add guard to prevent unnecessary parsing when text is empty in the LSP server's on_change handler. This prevents potential parser issues and improves robustness.

🐛 fix(lsp): handle empty text input in on_change method

---

crates/mq-formatter/src/formatter.rs

Fix spacing logic in block formatting by only appending space when the node doesn't have a newline. Also corrected the iteration to process all block children instead of skipping the first one.

🐛 fix(formatter): improve block spacing and newline handling

---

crates/mq-formatter/src/formatter.rs
crates/mq-hir/src/hir.rs
crates/mq-hir/src/resolve.rs
crates/mq-hir/src/symbol.rs
crates/mq-lang/src/ast/node.rs
crates/mq-lang/src/ast/parser.rs
crates/mq-lang/src/cst/node.rs
crates/mq-lang/src/cst/parser.rs
crates/mq-lang/src/eval.rs
crates/mq-lang/src/optimizer.rs
crates/mq-lsp/src/semantic_tokens.rs

This commit introduces support for calling functions dynamically using bracket access syntax (e.g., arr[0](), arr[0][1](args)). This enables storing functions in arrays or objects and calling them through index access.
Key changes:
- Added CallDynamic node type to CST and AST
- Implemented CallDynamic expression evaluation with call stack management
- Enhanced bracket access parsing to detect and handle function call syntax
- Improved HIR symbol handling for function parameters and arguments
- Fixed function parameter resolution by correctly marking them as Parameter symbols
- Refactored argument processing to handle complex nested expressions
- Added formatter support for CallDynamic expressions
- Added LSP semantic token support for CallDynamic symbols
- Included comprehensive test …

✨ feat(lang): add dynamic function call support
